export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as DetailsMovie } from './DetailsMovie/DetailsMovie'
export { default as LoginForm } from './LoginForm/LoginForm'
export { default as RegisterForm } from './RegisterForm/RegisterForm'
